version: "3.9"

services:
  # ─────────────────────────────
  # 1️⃣ Frontend Build (Next.js → static files)
  # ─────────────────────────────
  frontend-builder:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: frontend-builder
    working_dir: /app
    command: sh -c "echo 'Build complete, ready for nginx'"
    volumes:
      - web_static:/var/www/html
    # this container exits after building; not exposed
    restart: "no"

  # ─────────────────────────────
  # 2️⃣ Nginx Static Server
  # ─────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: sportbooking-web
    depends_on:
      - frontend-builder
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web_static:/var/www/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

# ─────────────────────────────
# Shared volume
# ─────────────────────────────
volumes:
  web_static:
