services:
  sportbooking-web:
    build:
      context: .
      dockerfile: Dockerfile.local   # keep this pointing at your current Dockerfile
    container_name: sportbooking-web
    ports:
      - "80:80"
    restart: unless-stopped
