services:
  sportbooking-web:
    build:
      context: .
      dockerfile: Dockerfile.local   # 👈 keep this name
    container_name: sportbooking-web
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
