version: "3.9"

services:
  sportbooking-web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: sportbooking-web
    restart: unless-stopped
    ports:
      - "80:80"
    # persist and inspect nginx logs on the host:
    volumes:
      - ./nginx/logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
