version: '3.8'

services:
  sportbooking-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportbooking-web
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      - NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-localhost}
      - NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE:-500M}
      - API_BASE_URL: ${API_BASE_URL:-http://api-server:3030/}
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - sportbooking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sportbooking-web.rule=Host(`${NGINX_SERVER_NAME:-localhost}`)"
      - "traefik.http.services.sportbooking-web.loadbalancer.server.port=80"

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: sportbooking-nginx-proxy
    ports:
      - "${PROXY_PORT:-8080}:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sportbooking-network
    depends_on:
      - sportbooking-web
    restart: unless-stopped
    profiles:
      - proxy

networks:
  sportbooking-network:
    driver: bridge
    name: sportbooking-network

volumes:
  logs:
    driver: local
