services:
  sportbooking-web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: sportbooking-web
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_SERVER_NAME=courtic.ir
      - API_BASE_URL=https://api.courtic.ir/
