version: '3.8'

services:
  # SportBooking Web Application
  sportbooking-web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: sportbooking-web-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=80
    networks:
      - sportbooking-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: sportbooking-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - sportbooking-web
    networks:
      - sportbooking-network

volumes:
  nginx-logs:

networks:
  sportbooking-network:
    driver: bridge
